name: Build Swift WebAssembly SDK

on:
    workflow_call:
        inputs:
            swift-release:
                description: 'swift toolchain release identifier'
                required: true
                type: string

jobs:
    WebAssembly:
        runs-on: ubuntu-24.04-arm
        steps:
            -   name: 💝 Install Swift 💝
                uses: rarestype/swift-install-action@v1
                with:
                    swift-release: ${{ inputs.swift-release }}

            -   name: 💝 Checkout 💝
                uses: actions/checkout@v6

            -   name: 💝 Checkout Swift project 💝
                uses: actions/checkout@v6
                with:
                    repository: swiftlang/swift
                    path: swiftwasm/swift
                    fetch-depth: 0

            -   name: 💝 Checkout related repositories 💝
                run: Scripts/Checkout
                env:
                    SWIFT_TAG: "swift-${{ inputs.swift-release }}"

            -   name: 💝 Build LLVM 💝
                run: Scripts/BuildLLVM

            -   name: 💝 Build Swift WebAssembly SDK 💝
                run: Scripts/BuildSDK
                env:
                    SWIFT_TAG: "swift-${{ inputs.swift-release }}"

            -   name: 💝 List bundles 💝
                run: |
                    ls -l swift-sdk-bundles

            -   name: 💝 Upload bundles 💝
                uses: actions/upload-artifact@v7
                with:
                    name: swift-sdk-bundles
                    path: swift-sdk-bundles/*.artifactbundle.zip
                    retention-days: 1
                    compression-level: 0
