name: Publish Swift WebAssembly SDK

permissions:
    contents: write
on:
    workflow_dispatch:
        inputs:
            swift-release:
                description: 'swift toolchain release identifier'
                required: true
                type: string

jobs:
    build:
        uses: ./.github/workflows/Build.yml
        with:
            swift-release: ${{ inputs.swift-release }}

    publish:
        runs-on: ubuntu-24.04-arm
        needs: build
        env:
            SWIFT_TAG: "swift-${{ inputs.swift-release }}"
        steps:
            -   name: 💝 Checkout 💝
                uses: actions/checkout@v6

            -   name: 💝 Download 💝
                uses: actions/download-artifact@v7
                with:
                    name: swift-sdk-bundles
                    path: release-artifacts

            -   name: 💝 Generate notes 💝
                run: |
                    download="https://github.com/${{ github.repository }}/releases/download"
                    notes="notes.md"
                    notes_footer="notes_footer.md"

                    echo "| bundle | checksum |" > "$notes"
                    echo "| ------ | -------- |" >> "$notes"

                    echo "" > "$notes_footer"

                    for zip in release-artifacts/*.zip; do
                        zip_file="${zip##*/}"
                        zip_checksum=$(sha256sum "$zip" | cut -d ' ' -f 1)

                        bundle_url="${download}/${SWIFT_TAG}/${zip_file}"
                        bundle_name="${zip_file%.artifactbundle.zip}"
                        bundle_name="${bundle_name#*-wasm32-unknown-}"

                        echo "| [\`${bundle_name}\`](${bundle_url}) | \`${zip_checksum}\` |" \
                            >> "$notes"

                        echo "" >> "$notes_footer"
                        echo "### ✰ ${zip_file%.artifactbundle.zip}" >> "$notes_footer"
                        echo '```' >> "$notes_footer"
                        echo "swift sdk install \"${bundle_url}\" --checksum ${zip_checksum}" \
                            >> "$notes_footer"
                        echo '```' >> "$notes_footer"
                    done

                    cat "$notes_footer" >> "$notes"

            -   name: 💝 Release 💝
                run: |
                    git config user.name "rarest automation"
                    git config user.email "automation@noreply.rarestype.com"

                    git tag -f "$SWIFT_TAG"
                    git push -f origin "$SWIFT_TAG"

                    gh release delete "$SWIFT_TAG" --cleanup-tag --yes || true
                    gh release create "$SWIFT_TAG" release-artifacts/*.zip \
                        --title "${{ inputs.swift-release }} ✰" \
                        --notes-file notes.md
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
