name: Publish Swift WebAssembly SDK

permissions:
    contents: write
on:
    workflow_dispatch:
        inputs:
            swift-release:
                description: 'swift toolchain release identifier'
                required: true
                type: string

jobs:
    build:
        uses: ./.github/workflows/Build.yml
        with:
            swift-release: ${{ inputs.swift-release }}

    publish:
        runs-on: ubuntu-24.04-arm
        needs: build
        env:
            TAG: "swift-${{ inputs.swift-release }}"
        steps:
            -   name: 💝 Checkout 💝
                uses: actions/checkout@v6

            -   name: 💝 Download 💝
                uses: actions/download-artifact@v7
                with:
                    name: swift-sdk-bundles
                    path: release-artifacts

            -   name: 💝 Generate notes 💝
                run: |
                    download="https://github.com/${{ github.repository }}/releases/download"
                    notes="notes.md"

                    echo "| ✰&nbsp; bundle | checksum |" > "$notes"
                    echo "| -------------- | -------- |" >> "$notes"

                    for zip in release-artifacts/*.zip; do
                        zip_file="${zip##*/}"
                        zip_checksum=$(sha256sum "$zip" | cut -d ' ' -f 1)

                        bundle_url="${download}/${TAG}/${zip_file}"
                        bundle_name="${zip_file%.artifactbundle.zip}"
                        bundle_name="${bundle_name#*-wasm32-unknown-}"

                        echo "| [❥ \`${bundle_name}\`](${bundle_url}) | \`${zip_checksum}\` |" \
                            >> "$notes"
                    done

            -   name: 💝 Release 💝
                run: |
                    git config user.name "rarest automation"
                    git config user.email "automation@noreply.rarestype.com"

                    git tag -f "$TAG"
                    git push -f origin "$TAG"

                    gh release delete "$TAG" --cleanup-tag --yes || true
                    gh release create "$TAG" release-artifacts/*.zip \
                        --title "${{ inputs.swift-release }}" \
                        --notes-file notes.md
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
